### ISSUE TITLE
fs option

### ISSUE THREAD

**Issue by frux** [webpack/webpack-dev-middleware#143]
I build my app for client and server. But I can't require rebuilded server scripts because of memory-fs. Can you give me availability to use custom file-system library (e.g. fs)?

**Comment by SpaceK33z** [comment]
webpack-dev-middleware is specifically made to handle and serve in-memory files. I don't understand your use case, could you explain that a bit more?

**Comment by SpaceK33z** [comment]
@otarim, is the config purely for the html files? You could use something like [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin) and pass config parameters to the plugin. In the html file you could then display those with underscore templates.

E.g. in your webpack config, add `new HtmlWebPackPlugin({ template: 'src/my-index.html', myConfig: 'blabla' })`. And then in `src/my-index.html`, include something like this: `<%=htmlWebpackPlugin.options.myConfig%>`.

**Comment by SpaceK33z** [comment]
Also see #88.

**Comment by SimeonC** [comment]
Hey, just came across this issue myself, so I found that the fs is exposed on the middleware here: https://github.com/webpack/webpack-dev-middleware/blob/6b49341db9c1323a1304ff99092036a72d2449a8/middleware.js#L83

And it's set here: https://github.com/webpack/webpack-dev-middleware/blob/6b49341db9c1323a1304ff99092036a72d2449a8/lib/Shared.js#L92

The problem I've found is that we can access the fs for the first render, but as the middleware is essentially setting an object reference - it doesn't update when we change it so I can't get a reference to the new FS. My use case is building a custom dev server for node-tailor which requires me to send the main js bundle through in a custom header. I have to restart the process to get the new file being sent through. This would be fixed by using a function to get the fs rather than relying on the object reference.

**Comment by tconroy** [comment]
hi @SimeonC - I'm trying to do an `fs.readFileSync` to read in a file from dev-middleware memory (I detailed my use case more over in #190). Can you elaborate how you got it working for your use case? I'm just trying to read-in a css file ( built by webpack ) into a node server environment so I can inject it in responses.

**Comment by shellscape** [comment]
closing given the discussion and apparent resolution and issue age. please request a reopen if needs be.
