### ISSUE TITLE
Issue with req.url and express mounted sub-apps

### ISSUE THREAD

**Issue by breachofmind** [webpack/webpack-dev-middleware#155]
Hey there,
I had some trouble getting this to work with a sub-app using express 4.x. `req.url` outputs the url relative to the sub-app and not the root app, which seems odd. As a result, this fails to match the url and returns false:
```javascript
// middleware.js, line 205
var filename = getFilenameFromUrl(options.publicPath, compiler.outputPath, req.url);
```
For example, a sub-app mounted to `/cms` with route `/static` will show `/static` instead of `/cms/static`.

This seemed to fix it:
```javascript
// middleware.js, line 205
var filename = getFilenameFromUrl(options.publicPath, compiler.outputPath, req.originalUrl);
```

**Comment by SpaceK33z** [comment]
Hmm this is tricky, [req.originalUrl](http://expressjs.com/en/api.html#req.originalUrl) also includes query parameters. We'd also need to use `req.originalUrl || req.url` for non-express users.

**Comment by dougwilson** [comment]
`req.url` also includes query parameters, so there is no difference there. If you want only the pathname, you'd have to parse it, regardless of `req.url` or `req.originalUrl`. The Express project provides a convenience module you are can use: `parseurl`

Include as `const parseUrl = require('parseurl')` and then instead of using `req.originalUrl || req.url`, you can use `parseUrl.original(req).pathname` and get the same behavior, plus not having the query parameters (which `req.url` does have, so not unique to `req.originalUrl` -- in fact, all `req.originalUrl` is is just a copy of what `req.url` was when the request first entered into the top-level Express application).

I hope this helps!

**Comment by shellscape** [comment]
@breachofmind if you can provide a full example setup that illustrates the problem, we can create tests from that and implement the solution that #192 proposed.

**Comment by shellscape** [comment]
@breachofmind this ticket is stale at 60 days and will be closed if there's no response from the community. last chance to weigh in 😅

**Comment by Kashmira9890** [comment]
socketexpress/node_modules/express-session/index.js:197
    var originalPath = parseUrl.original(req).pathname || '/'
                                             ^
TypeError: Cannot read property 'pathname' of undefined
    at session (socketexpress/node_modules/express-session/index.js:197:46)
