### ISSUE TITLE
Option for having bundle stay invalid in case of compilation error

### ISSUE THREAD

**Issue by mbergal** [webpack/webpack-dev-middleware#161]
I run flow and babel as webpack plugins and would like `webpack-dev-middleware` not to serve bundles with compilation errors

**Comment by SpaceK33z** [comment]
For what use-case? You removed the issue template which forces you into telling why, which is for a reason.

**Comment by mbergal** [comment]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

`webpack-dev-middleware` serves bundles with compilation errors in it 

**What is the expected behavior?**

`webpack-dev-middleware` has option to not serve bundles with compilation errors in it 


**If this is a feature request, what is motivation or use case for changing the behavior?**

I run flow and babel as webpack plugins and would like `webpack-dev-middleware` not to serve bundles with compilation errors

**Please mention your webpack and Operating System version.**
Webpack: 1.14.0

**Comment by rocketmonkeys** [comment]
I came here looking for this type of feature.  I'm not sure if it's the same resaon as @mbergal , but for me...

1) edit code
2) reload browser
3) browser is served the old bundle
4) look at terminal, see that webpack has a compilation error

So webpack is serving old files, which is odd.  I'd rather webpack delete bundle if there are compilation errors, so when I reload the browser I know immediately that something's wrong.  Often now I keep trying to debug things only to realize that I'm still seeing old code due to this, and I finally notice the compilation error.

**Comment by shellscape** [comment]
@rocketmonkeys we'd be happy to accept a PR (with tests!) to resolve this case.

**Comment by gregorskii** [comment]
Hey all in your custom dev server config you can add a express route to reload:

```
app.post('/reload', function(req, res, next) {
  hotMiddleware.publish({ action: 'reload' });
  next();
});
```

Then you can have whatever tool is watching the files outside of webpack run a post against that URL.

Ensure that that URL is not being forwarded back to a proxy (like Python, PHP etc)  by excluding it from the proxy in `proxyMiddleware` if used.

**Comment by shellscape** [comment]
solid workaround @gregorskii 👍

**Comment by shellscape** [comment]
@mbergal this ticket is stale at 60 days and will be closed if there's no response from the community. last chance to weigh in 😅
