### ISSUE TITLE
404 with koa on 1.11.0

### ISSUE THREAD

**Issue by dlebedynskyi** [webpack/webpack-dev-middleware#202]
* Operating System: mac
* Node Version: 8.0.0
* NPM Version: 5.0.0
* webpack version: 2.6.1
* webpack-dev-middleware Version: 1.11.0

This is a **bug** after update from 1.10.2

### Code
using koa (2.3.0) to start assets server on another domain (3000). 
all request that are being send from main page (:3001) get 404. 
Opening `localhost:3000/app.js` in browser tabs returns content. 

I suspected it is some weird behavior for cors. 

Assets server 
```js
const Koa = require('koa');
const serve = require('koa-static');
const e2k = require('express-to-koa');
const devMiddleware = require('webpack-dev-middleware');

const app = new Koa();

    app.use(async (ctx, next) => {
      ctx.set('Access-Control-Allow-Origin', '*');
      await next();
    });

    app.use(serve(PUBLIC));
   const compiler = webpack(devConfig);
   app.use(
      e2k(
        devMiddleware(compiler, {
          noInfo: true,
          quiet: true,
          host: config.environment.hostname,
          headers: { 'Access-Control-Allow-Origin': '*' },
          publicPath: '/',
          stats: {
            colors: true,
            reasons: false,
          },
        })
      )
    );

app.listen(3000);

```
### Expected Behavior

1.10.2 returns assets just fine. 

### Actual Behavior

1.11.0 returns 404 instead

### For Bugs; How can we reproduce the behavior?
1. start server from script above
2. start any other node server on http://localhost:3001/ that request http://localhost:3000/app.js  

Note: app.js is compiled script - in our case React app. Any other static asset from PUBLIC folder are served just fine. 
This behavior only changed for webpack dev server assets

**Comment by shellscape** [comment]
`express-to-koa` shouldn't be required any longer, and I'd recommend using `koa-webpack` over that with `webpack-dev-middleware`. Also, see https://github.com/webpack/webpack-dev-middleware/pull/177 (was mentioned in the release) which may now conflict with `express-to-koa`. also, I'd highly recommend using `koa-cors` over a custom solution, it's fairly streamlined.

I'll leave this one open for a bit in case there's a legit bug found in the code for the module, but I'm thinking that this is moreso a support issue.

**Comment by mnquintana** [comment]
@shellscape We're also running into this issue, but with `webpack-dev-server` (`2.4.5` and `2.5.0`) rather than koa. All assets served by `webpack-dev-server` (with `webpack-dev-middleware` 1.11.0 under the hood) return 404s. FWIW, we have another server sitting in front of `webpack-dev-server` proxying requests to `/assets` on to it. We didn't have this problem when `webpack-dev-server` was depending on `webpack-dev-middleware@1.10.2`.

We're running `webpack@2.6.1`.

Is there any more information I could provide that'd be helpful?

**Comment by shellscape** [comment]
I'm honestly not sure. Both of your setups sound far more complex than what I've run with either module. This is probably going to take one of you debugging the handlers within your setups to figure out a fix.

**Comment by mnquintana** [comment]
It looks like the proxying isn't relevant to this issue - I've managed to reproduce this with just `webpack-dev-server@2.4.5` running locally, and trying to request asset URLs in the browser.

**Comment by eudaimos** [comment]
@dlebedynskyi generally I don't use `koa-static` in my dev setup when I want to serve assets via the `webpack-dev-middleware` - that could be getting in the way, since `webpack-dev-middleware` is going to keep everything in memory in a virtual filesystem, there won't be anything for `koa-static` to serve.

Also, like @shellscape said, you should use `koa-webpack` to wrap the `webpack-dev-middleware` which will provide koa-based handlers that use `async` functions to ensure the middleware chain executes correctly.  Otherwise, the `webpack-dev-middleware` handlers will execute synchronously and likely the koa application ends up "handling" the request if the dev middleware isn't done retrieving the desired file contents, in which case the koa application will fallback to empty body with 404.  You can verify this behavior by checking the `content-type` of the response and seeing if it's set to `text`.

**Comment by dlebedynskyi** [comment]
@eudaimos I usually don't use koa-static for dynamic assets, but in this case we need to serve some public static files. 
> , you should use koa-webpack
koa-webpack might be an options but need to test it with webpack-dev-middleware@1.11
