### ISSUE TITLE
How to catch end of compilation event in express side

### ISSUE THREAD

**Issue by dmnBrest** [webpack/webpack-dev-middleware#219]
Hello, 
I have just started with your middleware and I have small question.
Is there a way to catch event when compilation is over after code updates.
I see in console
...
    + 86 hidden modules
webpack: Compiled successfully.
And I want to fire one post job.
I thought webpackDevMiddlewareInstance.waitUntilValid should help me, but it fire just one time after server start and not working on every compilation event.
I saw there is a webpack-hot-middleware but all examples are related with browser. I just need to server side event.

I would be appreciated for any examples!

Thanks!

**Comment by shellscape** [comment]
@dmnBrest it looks like you might possibly be new to Github, so hopefully you find this info useful. citing the issue template:

> The Issues page for this repository is not a support forum. **Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). Questions will be closed.** If you proceed with this form, please fill out **_all_** fields, or your issue may be closed as "invalid." Please do not delete this template from a new issue. Please remove this header to acknowledge this message.

That's an important chunk of info right there. We're going to close this issue for a few reasons;

- you removed/deleted the issue template. that's generally frowned upon on Github. if you see an issue template, you should always fill it out.
- your issue is a general support question. while we'd love to help you, this isn't the right forum for that, as outlined in the snippet from the issue template I pasted above.
- there are two support options for you listed in the issue template to try. additionally, you can always tweet with the hashtag #webpack and someone is likely to help out there as well
