### ISSUE TITLE
Serving static html at landing page in dev server

### ISSUE THREAD

**Issue by thekevinscott** [webpack/webpack-dev-middleware#227]
## Goal
**Using webpack dev server, I want to serve a landing page `landing.html` for `/`, and the rest of my react app on any other route (aka, `/foo`).**

It appears this is supported according to the [webpack docs](https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option) but is not working on a [`create-react-app` app](https://github.com/thekevinscott/sample-webpack-failing-historyApiFallback).

*If this is *not* supported please let me know and I'll close this issue! And I'm not sure if `webpack-dev-middleware` is the right repo (vs. `webpack` or one of the other ones), happy to move this if in the wrong place.*

I've [created a StackOverflow question](https://stackoverflow.com/questions/47273319/matching-root-route-in-webpack-dev-servers-historyapifallback/47275941#47275941) but received no resolutions.

## Overview

* Operating System: macOS Sierra 10.12.6
* Node Version: v8.2.1
* NPM Version: 5.5.1
* webpack version: 3.8.1
* webpack-dev-middleware Version: 1.12.0

- [ x ] This is a **bug**

### Code

[Repo demonstrating the issue is here](https://github.com/thekevinscott/sample-webpack-failing-historyApiFallback).

Relevant code from `webpackDevServer.config.js` ([originally taken from the docs](https://webpack.github.io/docs/webpack-dev-server.html#the-historyapifallback-option)):

```
module.exports = function(proxy, allowedHost) {
  return {
    ...
    historyApiFallback: {
      // Paths with dots should still use the history fallback.
      // See https://github.com/facebookincubator/create-react-app/issues/387.
      disableDotRule: true,
      rewrites: [
        // shows views/landing.html as the landing page
        { from: /^\/$/, to: "landing.html" },
        // shows views/subpage.html for all routes starting with /subpage
        { from: /^\/subpage/, to: "subpage.html" },
        // shows views/app.html on all other pages
        // but doesn't work for routes other than app.html
        { from: /./, to: "app.html" }
      ]
    },

    ...
  };
}
```

### Expected Behavior

When going to `http://localhost:3000`, I expect to see `landing.html`.

### Actual Behavior

When going to `http://localhost:3000`, I see the react app served.

### For Bugs; How can we reproduce the behavior?

1) [Clone the repo](https://github.com/thekevinscott/sample-webpack-failing-historyApiFallback)
2) Run with `yarn start` (or `npm run start`)
3) Go to `http://localhost:3000`
4) Observe the default `create-react-app` screen

### Some preliminary investigation from my end

It looks like in [`processRequest`](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L45), for a route like `/subpage` the call to `stat` fails and gets picked up by `goNext()`; but for a blank route, like my landing page, it defaults to `index.html` and never gets to the `connect-history-api-fallback`.

**Comment by shellscape** [comment]
Yeah this is probably not the right repo. webpack-dev-server would be a logical choice.

While we don't generally leave support requests open, it's hard to tell if this is an actual bug or just another nuance of `create-react-app`. I'd recommend working with that project first and foremost, as they should be able to let you know if it's a limitation on their end to begin with. We know for absolute certain that `historyFallbackApi` works correctly/as-expected in `webpack-dev-server`, and we have tests and an example around that. Given that, your next stop should be the `history-fallback-api` project with a minimum example of a feature not working as well.

Secondly, in order to call this a bug - and not an edge case related to the addition of another framework and dependency tree - we need to know that it's reproducible in a minimum-viable-example. It's certainly appreciated that you created the referenced repo to demonstrate the issue, but we can't (just don't have time) to wade through create-react-app looking for the culprit. Taking one of the [`examples`](https://github.com/webpack/webpack-dev-server/tree/master/examples) as a base, you could use the [`history-api-fallback` example](https://github.com/webpack/webpack-dev-server/tree/master/examples/cli/history-api-fallback) and work from there to reproduce similar results that you're after. And if that's not possible, follow up with one of the afore mentioned projects.

We'll leave this open in the event you can pinpoint a bug in WDM or WDS, but it doesn't look like a bug on the surface.

**Comment by thekevinscott** [comment]
Very much appreciate the detailed response - and totally understood. I'll look through the examples first, and if things are working fine close this issue and pursue with the aforementioned projects. Thank you @shellscape!

**Comment by thekevinscott** [comment]
This is not a bug and I will close this issue.

Some more context in case others come across this via Googling: The issue was using `HtmlWebpackPlugin` alongside `historyApiFallback`.

It looks like `HtmlWebpackPlugin` (and maybe all plugins?) get processed prior to hitting the `historyApiFallback` route matching. If `HtmlWebpackPlugin` is set up with its defaults, it will produce an output file at `index.html`, which will trigger the stat call in [`processRequest`](https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L45) and prevent the landing page regex from ever being reached.

The solution in my case is to set up a custom `filename` in `HtmlWebpackPlugin` that is not `index.html`, and explicitly route via wildcard to that filename. That prevents a landing page from being matched (and allows me to control matching via `historyApiFallback`). [I don't see this explicitly called out in their docs](https://github.com/jantimon/html-webpack-plugin#configuration) but it works great.

[Here's a sample repo](https://github.com/thekevinscott/sample-webpack-fixed-apiHistoryfallback) showing `historyApiFallback` working alongside `HtmlWebpackPlugin`.

Thanks for a solid library and sorry for the false alarm!
