### ISSUE TITLE
option to not use memory-fs

### ISSUE THREAD

**Issue by Rich-Harris** [webpack/webpack-dev-middleware#239]
* Operating System: macOS Sierra
* Node Version: 9.1.0
* NPM Version: 5.5.1
* webpack version: 3.10.0
* webpack-dev-middleware Version: 2.0.1

- [x] This is a **feature** request
- [ ] This is a **bug**

### Code

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### For Bugs; How can we reproduce the behavior?

N/A

### For Features; What is the motivation and/or use-case for the feature?

Would you accept a PR that added an `fs` option? I have a scenario where I need to generate some secondary assets based on the `stats` object — in dev mode, the stats come straight from the `compiler.watch` callback, but in prod mode they're read from JSON files on disk produced at build time. Accommodating two separate filesystems creates a surprising amount of extra code, and introduces unnecessarily tight coupling between the different parts of the system.

Beyond that, writing files to disk is advantageous from the point of view of understanding what work webpack is doing, and debugging when things go wrong, because I can see the files in my editor. There might be a theoretical perf hit but a) on modern computers it's truly negligible, and b) it's *dev* middleware, so I'd argue that the aforesaid advantages take priority.

My proposal:

```js
app.use(middleware(compiler, {
  fs: false // don't create a new memory-fs instance, just use compiler.outputFileSystem
}));

const fs = require('fs');
app.use(middleware(compiler, {
  fs // use *this* outputFileSystem
}));
```

**Comment by michael-ciniawsky** [comment]
```js
compiler.outputFileSystem = require('fs') 
```

https://www.npmjs.com/package/write-file-webpack-plugin

**Comment by Rich-Harris** [comment]
Thanks, but write-file-webpack-plugin seems like a very complicated solution to a very simple problem. I don't want to have to start adding and configuring new plugins, and telling my users to do the same, just to achieve webpack's normal behaviour.

I tried setting `compiler.outputFileSystem = require('fs')` but I got this error — 

> TypeError: this.outputFileSystem.mkdirp is not a function

— so maybe it just won't be possible to use the normal `fs` with webpack-dev-middleware?

If that's the case, I'd be grateful if anyone can help me figure out how to use webpack-hot-middleware *without* webpack-dev-middleware, because that's the only reason I'm currently using it. Thanks!

**Comment by shellscape** [comment]
@Rich-Harris please do edit your original issue and fill out the issue template (if the language in the template didn't indicate that it was non-optional please suggest ways to improve that). we ask this of every contributor :heart:

**Comment by michael-ciniawsky** [comment]
> Thanks, but write-file-webpack-plugin seems like a very complicated solution to a very simple problem. I don't want to have to start adding and configuring new plugins, and telling my users to do the same, just to achieve webpack's normal behaviour.

Yeah... I understand that very well :), it's just a suggestion of one way I know of

>  so maybe it just won't be possible to use the normal fs with webpack-dev-middleware?

It should be possible, but `fs` doesn't seemed to be a 💯 drop-in replacement for `memory-fs` (I thought it is API compatible 😞) and this sadly also needs some (additional) manual effort to get it working then.

```js
const fs = require('fs')
const mkdirp = require('mkdirp')
...

const filesys = {
   ... 'shim' memory-fs methods 1:1 
}

compiler.outputFileSystem = filesys
```

If a small option in the `dev-middleware` can easily provide this ignore me and the noise here 😛

**Comment by Rich-Harris** [comment]
@shellscape updated, sorry. It's a very long template and it mostly seemed to pertain to bug reports rather than feature requests/discussions — I didn't think Node version etc would be relevant. My bad!

@michael-ciniawsky It turns out that it doesn't matter whether memory-fs is a drop-in replacement or not (though, side-note, I'm very surprised that it's not 😀) — setting `compiler.outputFileSystem` doesn't reset all the internal references, so files end up not getting served.

**Comment by michael-ciniawsky** [comment]
@Rich-Harris Yep, you're right the simplest way is to just add an option to `emit` the files somewhere around [here](https://github.com/webpack/webpack-dev-middleware/blob/master/lib/util.js#L151), so `webpack-dev-middleware` doesn't override the `compiler.outputFileSystem` with an `MemoryFS` instance :)

**Comment by liuyunzhuge** [comment]
Memory-fs is not convenient for debug。

**Comment by shellscape** [comment]
since all that block is doing is essentially setting `compiler.outputFileSystem`, those who are in need of this should create a new class that inherits from `MemoryFileSystem` to generate the behavior they're seeking. I'd recommend rolling that into a reusable module that can be shared.

alternatively, folks can use the existing filesystem to list and read files in the memoryfs in a similar manner in which webpack-dev-server does https://github.com/webpack/webpack-dev-server/blob/00e8500b0853312be3cf369976509fbce2a4b7dc/lib/Server.js#L121

Adding this option would introduce a significant bit more testing, new vectors for errors (someone introduces a bad `fs` to the option), and oodles more conditional checking. All that said, this isn't a feature that's been _widely_ in demand, and given that there's a couple of pretty clear paths - one of which that could be rolled into a complementary module itself - for resolving this on the user's end, this won't be an option we're going to allow for in webpack-dev-middleware itself.

Feel free to continue discussing on this thread.

**Comment by salemhilal** [comment]
@shellscape Sorry to dig this topic back up. I'm working on a pretty large project, and having files written in memory (in addition to all of the things webpack keeps around after a build) makes the memory footprint of a dev server quite large.

Instead of tricking webpack-dev-middleware into believing it's been given an in-memory filesystem when it's really doing otherwise (i.e. by extending `MemoryFileSystem` and returning the same methods set in [`NodeInputFileSystem`](https://github.com/webpack/webpack/blob/master/lib/node/NodeOutputFileSystem.js), is there harm in just sidestepping the call to `setFs` if an option is present? Specifically, I'm looking at this line, and would expect the implementation to be similar to how `writeToDisk` is set:

https://github.com/webpack/webpack-dev-middleware/blob/master/index.js#L64-L69

If you're not opposed, I'm happy to open a pull request.

**Comment by salemhilal** [comment]
@shellscape A fork may be a possible route. Can you speak more to the complexity you'd worry about?
