### ISSUE TITLE
watchOffset possibly skewing build time for webpack 4

### ISSUE THREAD

**Issue by alexzherdev** [webpack/webpack-dev-middleware#268]
* Operating System: macOS 10.13.2
* Node Version: 9.2.0
* NPM Version: 5.5.1
* webpack version: 4.0.1
* webpack-dev-middleware Version: 2.0.6

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code
Created an empty project with these two files (plus `package.json`) to reproduce.

```js
// src/index.js
console.log('index');
```

```js
// server.js
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');

const compiler = webpack({});

new WebpackDevServer(compiler, {}).listen(3000, 'localhost');
```

### Expected Behavior
Build output in the console reports actual build time.
### Actual Behavior
Build output contains incorrect build time of 11+ seconds (e.g. `Time: 11088ms`) when in reality it's almost instantaneous.
### For Bugs; How can we reproduce the behavior?
I'm using `webpack-dev-server` but I don't believe the issue is specific to that project.
I was able to trace it down to the `watch-run` hook at `webpack-dev-middleware/lib/context.js:114`, where `watcher.startTime` is undefined.
```
    if (options.watchOffset > 0) {
      watcher.startTime += options.watchOffset;
    }
```
Meaning that after this operation `watcher.startTime` is `NaN`. However, the `done` handler in the same file is able to offset `startTime` backward, because `stats.startTime` does contain an integer value at that moment.
```
stats.startTime -= options.watchOffset;
```
Combined, these two lines effectively add `watchOffset` to the reported build time.

**Comment by shellscape** [comment]
Thanks for the issue 🍺 

Yeah, that tended to munge the build times at random when running in the context of a dev server, which in the grand scheme of things was preferable to watchpack causing n-number of repeated builds. You can read more about that here: https://github.com/webpack/watchpack/issues/25. You're seeing that with webpack v4 because that particular hook changed signature. 

FWIW this has been removed as of https://github.com/webpack/webpack-dev-middleware/commit/fbad3a9543fa90e08ccb7c5edbd3bcb9e2dc1c31#diff-d911385a221c0b7502eabe1fdac9d209L102, and the documentation is going to be updated to recommend people use https://github.com/egoist/time-fix-plugin when we're ready for release of v3.0.0.

For v2.0.0 that's going to remain in place, and folks like yourself using webpack v4.0.0 can move to WDM@3.0.0 when we release that (soonish).
