### ISSUE TITLE
Does this work with hot loading?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack-dev-middleware#29]
I see `WebpackDevServer` comes with special support for hot loading. Middleware does not seem to include it. Is it possible to use the middleware with hot loading somehow?

**Comment by sokra** [comment]
webpack-dev-server uses webpack-dev-middleware

You can use HMR, but you need to implement the change notification by yourself.

**Comment by bebraw** [comment]
Ok, thanks!

I had a look at code. Maybe it would make sense to separate the HMR bit so it's easier to compose but apart from that we can probably consider this issue resolved.

Incidentally I noticed that `WebpackDevServer` supports `historyApiFallback` argument. Given it was not documented yet, I added a note about it at the docs so it is easier to find.

**Comment by sokra** [comment]
:+1:

**Comment by dtothefp** [comment]
@bebraw did you ever figure this out? I'm a little confused when @sokra says "you need to implement the change notification by yourself". Could one of you point me in the right direction?

**Comment by bebraw** [comment]
@dtothefp Middleware was too low level for my purposes after all. `historyApiFallback` did exactly what I needed. I wanted to access the site from any url (not just root) and enabling that helped me to do that. Here's an example without imports:

```
new WebpackDevServer(webpack(config), {
    publicPath: config.output.publicPath,
    hot: true,
    historyApiFallback: true,
}).listen(port, ip, function (err) {
    if(err) {
        return console.log(err);
    }

    console.log('Listening at ' + ip + ':' + port);
});
```

@dtothefp Can you describe your use case?

**Comment by dtothefp** [comment]
@bebraw thanks, I'm familiar with the `webpack-dev-server` and have used it quite a bit. I'm currently working on a project where they have a small `express` server serving frontend assets locally. I've successfully add the `webpack-dev-middleware` to the `express` server but want to figure out how to get hot module replacement working. 

Generally I use `webpack.HotModuleReplacementPlugin` in combo with the config you have above and 

```
var devScripts = [
    'webpack-dev-server/client?http://localhost:' + options.port,
    'webpack/hot/only-dev-server',
  ]
```

bundled with my entries. If I add the first script ` 'webpack-dev-server/client?http://localhost:' + options.port` this throws an error in `Socket.io` in the `webpack-dev-server`

**Comment by dtothefp** [comment]
@sokra could you please give me some advice on `hot-module-replacement` with `webpack-dev-middleware`. I cloned your [example app](http://webpack.github.io/example-app/) but still didn't completely get it. In that app 

```
module.hot.apply(function(err, renewedModules) {
	if(err) return hotResult.text(err.toString());
	if(renewedModules) hotResult.text("Renewed modules: " + renewedModules.join(", "));
});
```
`module.hot.status()` continually throws an error (as expected from the docs) because it doesn't `!== ready`. I setup an example repo and from the code [here](https://github.com/dtothefp/webpack-middleware-test/blob/master/lib/index.js) I thought that all JS in the `/views` directory would work with `hot-module-replacement`. 

I'm a little confused from the docs and the example app, as I can't figure out what handlers to apply to create `hot-module-replacement` with scripts using the `webpack-dev-middleware`

**Comment by sokra** [comment]
@dtothefp You need to call `module.hot.check` first before using `module.hot.apply`. The "example-app" is pretty old and the API changed in between.

http://webpack.github.io/docs/hot-module-replacement.html#management-api

**Comment by dtothefp** [comment]
@sokra I actually am calling `check` here 

https://github.com/dtothefp/webpack-middleware-test/blob/master/lib/index.js#L32

but was getting errors because it kept telling me `check` is only allowed in `idle` status. It seems some sort of recursive loop because if on page load I call `module.hot.status()` the status is `"idle"`. But, when I call `module.hot.check` the status becomes `"check"` and the `check` method throws an error. It seems the middleware is difficult to setup with hot loading, so I will probably move more towards the technique you mentioned here

https://github.com/gaearon/react-hot-loader/issues/46#issuecomment-66960643

**Comment by sokra** [comment]
hmm... It shouldn't be so complex. Take a look at the file in [`webpack/hot`](https://github.com/webpack/webpack/tree/master/hot) which feature some HMR management implementations.

**Comment by mattpage** [comment]
For anybody that is struggling with getting HMR working, I created a node module that implements HMR on top of  webpack-dev-middleware. You can find it [here](https://github.com/mattpage/webpack-dev-hmr).

**Comment by pixeldrew** [comment]
another module that works: https://www.npmjs.com/package/webpack-hot-middleware
