### ISSUE TITLE
WDM doesn not call next middleware on bundle compilation

### ISSUE THREAD

**Issue by cdxOo** [webpack/webpack-dev-middleware#374]
* Operating System: GNU/Linux 4.20.0-arch1-1-ARCH #1 SMP PREEMPT x86_64
* Node Version: 11.10.0 and 8.15.0
* NPM Version: 6,8,0 and 6.7.0
* webpack version: 4.29.5
* webpack-dev-middleware Version: 3.6.0

- [ ] This is a **feature** request
- [x] This is a **bug**

### Code
code in [cdxOo/webpack-dev-middleware-next-call-mrr](https://github.com/cdxOo/webpack-dev-middleware-next-call-mrr) under src/; main file is test.js; webpack config in ./config/webpack.js
run

    npm install
    npm test

### Expected Behavior
next middleware is called after bundle compilation is done 

### Actual Behavior
next middleware is NOT called when bundle compiles

### For Bugs; How can we reproduce the behavior?
i put up an automated test in the given repositoy; run via "npm test"

**Comment by evilebottnawi** [comment]
@cdxOo Thanks for PR, feel free to send a PR with fix

**Comment by evilebottnawi** [comment]
@cdxOo sorry for big delay, not sure it is bug, because when we do build we don't known all assets, so i think we should wait before webpack done compilation otherwise you will be error 404 in some cases

**Comment by evilebottnawi** [comment]
After investigate and comparing with `serve-static` (https://github.com/expressjs/serve-static) i can't find here problem, we have same behavior as `serve-static`.

If file found we `send` it and stop handling (as do `serve-static`), if file not found we call next middleware. I don't think it is bug so i closing issue, anyway if you disagree with this, please open new issue and describe why do you think otherwise. Sorry for long delay.
