### ISSUE TITLE
Start emitting chunks only once requested

### ISSUE THREAD

**Issue by bhollis** [webpack/webpack-dev-middleware#622]
- Operating System: macOS 0.14.6
- Node Version: v13.5.0
- NPM Version: 6.13.4
- webpack Version: 4.42.1
- webpack-dev-middleware Version: 3.7.2

### Feature Proposal

What I'd like is a sort of variant of `lazy` mode, where a particular chunk would only be built if it is requested by the browser, but after that it is watched and can hot-load. 

This project appears to implement something like what I'm looking for, but I was unable to get it to work - it'd be much nicer if this was built into Webpack: https://github.com/tfoxy/webpack-lazy-dev-build

### Feature Use Case

I have a large project which uses dynamic imports to do a lot of code-splitting - my users only download what they need, when they need it. However, when I start the dev server, it builds the entire project right away, which is very slow. If I had this option, when I'm working on one area of my app I never need to build all the parts I'm not working on.

**Comment by evilebottnawi** [comment]
> What I'd like is a sort of variant of lazy mode, where a particular chunk would only be built if it is requested by the browser, but after that it is watched and can hot-load.

It was once realized, but it was deleted, since we do not have all stats until a full compilation is completed. I’m afraid it’s not possible to create due to design and many limitations. We should focus on improving performance, if you create an application repository that you want, I could see how it can be improved.

**Comment by bhollis** [comment]
Thanks for the response! For dev-server, does the hash matter particularly? I figured that was only for production long-term caching and could be omitted during development. 

Feel free to check out https://github.com/DestinyItemManager/DIM - it’s a fairly large open source project that puts Webpack through its paces. You should be able to just check it out and run `yarn && yarn start` - no need to fully set up for development just to test the dev server or build.

**Comment by evilebottnawi** [comment]
@bhollis 

>  I figured that was only for production long-term caching and could be omitted during development.

unfortunately we cannot, hashes can be used anywhere

> Feel free to check out https://github.com/DestinyItemManager/DIM - it’s a fairly large open source project that puts Webpack through its paces. You should be able to just check it out and run yarn && yarn start - no need to fully set up for development just to test the dev server or build.

This solution relies on some invalid solutions from webpack, but in general it is wrong. Yes, it can be implemented, but for limited cases. We cannot ship that as good solution. Developers begin to use it in all possible variations and this leads to problems. Therefore, we decided not to do this. Instead of this, I would suggest you do refactoring, maybe revisit structure.

**Comment by bhollis** [comment]
Sounds good. I’d be interested to know which refactorings you think would help - maybe splitting the project into multiple independent Webpack configurations? In general I’ve liked having webpack be able to choose chunk splitting on its own.
