### ISSUE TITLE
couldn't use res.locals.webpack after serverSideRender is enabled

### ISSUE THREAD

**Issue by abdulghani** [webpack/webpack-dev-middleware#684]
```typescript
const server = express();
const compiler = webpack(webpackConfig);

server.use(webpackDevMiddleware(compiler, { serverSideRender: true }));
server.use((req: Request, res: Response) => {
  const { devMiddleware } = res.locals.webpack;  // this one is not exist in res.locals object
  const outputFileSystem = devMiddleware.outputFileSystem;
  const jsonWebpackStats = devMiddleware.stats.toJson();
  const { assetsByChunkName, outputPath } = jsonWebpackStats;
  
  // rest of the operation
});

```
it doesn't give the `webpack` object to the `res.locals` object.

I'm using react config that's generated by `react-scripts@3.4.1`
and my `webpack-dev-middleware` is in `3.7.2`

is this thing still suppose to work?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Because you read docs for https://github.com/webpack/webpack-dev-middleware/tree/v3.7.2, in the master branch we have `rc`.

https://github.com/webpack/webpack-dev-middleware/tree/v3.7.2#server-side-rendering
