### ISSUE TITLE
Multicompiler publicPath doesn't recognize root folder

### ISSUE THREAD

**Issue by VitaliiPyvovar** [webpack/webpack-dev-middleware#854]
- Operating System: macOS Catalina version 10.15.5
- Node Version: v14.15.1
- NPM Version: 6.14.8
- webpack Version: 4.46.0
- webpack-dev-middleware Version: 4.1.0

**Identical setup worked fine on webpack-dev-middleware Version: 3.7.0**

### Code

```js
const webpack = require('webpack');
const middleware = require('webpack-dev-middleware');
const express = require('express');

const app = express();
const compiler = webpack([{
    ...options for first compiler,
    output: {
        filename: '[name].js',
        path: '.../build/a',
        publicPath: '/static/a'
    },
}, {
    ...options for second compiler,
    output: {
        filename: '[name].js',
        path: '.../build/b',
        publicPath: '/static/b'
    },
}]);

app.use(
  middleware(compiler, {
      publicPath: /static/,
  })
);
app.listen(3000, () => console.log('Example app listening on port 3000!'));
```

The structure of the build folder is
```
build
  ↳ a
    ↳ some-a.js
  ↳ b
    ↳ some-b.js
  ↳ some.js    
```
Note: some.js is copied in the build/ folder by `copy-webpack-plugin`

### Expected Behavior

We should be able to fetch `/static/a/some-a.js`, `/static/b/some-b.js` and `/static/some.js`.

### Actual Behavior

`/static/some.js` is interpreted as an app route, not as a source file.

### How Do We Reproduce?

Try to use a MultiCompiler where each of the compilers has a output.publicPath that contains a `/static/smth` and then try to use `/static/` as a publicPath config to a `webpack-dev-middleware`.

**Comment by alexander-akait** [comment]
When you specify `publicPath` for middelware you will use this public path for both compilers, you need specify publicPath for each compiler to support it

**Comment by alexander-akait** [comment]
Can you provide simple example?

**Comment by VitaliiPyvovar** [comment]
@alexander-akait https://github.com/VitaliiPyvovar/webpack-dev-middleware-issue-ilustration - this repository contains a working solution using webpack-dev-middleware version 3.7.0 in master branch, and broken one in with-error branch featuring webpack-dev-middleware version 4.1.0

**Comment by alexander-akait** [comment]
Do you want to use the `publicPath` option for `middleware` or allow to using it for each compiler (i.e. no the `publicPath` option for middleware)?

**Comment by VitaliiPyvovar** [comment]
@alexander-akait both options are fine, in my case either specifying `publicPath` for both compilers as `/static/` or specifying `publicPath` in `middleware` options as `/static/`. The point is to fix `middleware` to interprete right any of this solutions, as it was in `3.7.0` version.

**Comment by alexander-akait** [comment]
Sorry for delay, that is because you have multiple `output.path` for each compiler, and `some.js` outside from your compiler paths, example you have `/static/some.js`, we understand what `/static/some.js` should be handled webpack-dev-middleware due `/static/` value, then  we add `output.path` to your request, i.e. we try to search files:
- /path/to/build/a/some.js
- /path/to/build/b/some.js

but no files founds, how you can fix it? change `output.path` for each compiler on `build` and set `a/filename: '[name].js',` and `b/ filename: '[name].js',` for compilers, you can't load/handle files out of `output.path`. It can be unsafe because you can read file above your configured `output.path` and it's not safe, you have security files, like `.env` and etc. feel free to feedback
